### PR TITLE
Major Styling

### PR DESCRIPTION
**Pull request by nathanielmillard**
## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please describe):

## Problem/feature
-We needed a HUGE amount of styling

## Solution
-Refactoring the side bar into a recipe footer
-Restyling basically everything

### Main Page Before:
Screen Shot 2021-01-12 at 7 44 34 PM

### Main Page Now:
Screen Shot 2021-01-13 at 12 10 29 PM

### Profile Before
Screen Shot 2021-01-12 at 7 44 53 PM

### Profile Now:
Screen Shot 2021-01-13 at 12 11 41 PM

###Call To Action Before:
Screen Shot 2021-01-13 at 12 14 56 PM

### Call To Action Now:
Screen Shot 2021-01-13 at 12 13 08 PM

### Sign In Before:
Screen Shot 2021-01-13 at 12 14 30 PM

### Sign In Now:
Screen Shot 2021-01-13 at 12 13 54 PM

## Checklist
- [ ] Code compiles correctly
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by hashmaster3k — APPROVED** [review]
Wow! That looks so great! I like how the navigation bar is at the bottom instead of the top. It feels like it gives way for you to experience the app more than adding yet another bar to the top of the screen.

**Comment by coreycartercodes** [comment]
Wondering if we have a logo we can drop on that SignUp/SignIn page?

Otherwise looks great! I'm still not team GamGam but It turned out beautiful! 😂

Thank you Nathaniel!

**Review by coreycartercodes — APPROVED** [review]
See Logo Comment on main conversation. Looks great!

**Review by BrigetteDoelp — APPROVED** [review]
Beautiful! Love the style direction!

**Comment by nathanielmillard** [comment]
> Wondering if we have a logo we can drop on that SignUp/SignIn page?
> 
> Otherwise looks great! I'm still not team GamGam but It turned out beautiful! 😂
> 
> Thank you Nathaniel!

We don't have a formal logo yet but the app name is in the bottom left is there on every page navigation including the sign in/up pages and it's a clickable nav to get to the global recipe store from anywhere.

**Pull request merged**
